namespace: aidp

modelApi:
  enabled: true
  image:
    repository: ghcr.io/raptorex65/aidp-model-api
    tag: latest
    pullPolicy: Always
  replicas: 1
  servicePort: 8080
  containerPort: 8080

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  servicePort: 5432
  storage:
    size: 2Gi

minio:
  enabled: true
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: IfNotPresent
  mcImage:
    repository: minio/mc
    tag: latest
    pullPolicy: IfNotPresent
  servicePort: 9000
  consolePort: 9001
  storage:
    size: 2Gi
  bucketName: mlflow

mlflow:
  enabled: true
  image:
    repository: ghcr.io/raptorex65/aidp-model-api
    tag: latest
    pullPolicy: Always
  replicas: 1
  servicePort: 5000
  containerPort: 5000

ingress:
  enabled: true
  className: nginx
  host: aidp.local
  paths:
    api: /api
    mlflow: /mlflow

resources:
  modelApi: {}
  mlflow: {}
  postgres: {}
  minio: {}

labels:
  app: aidp
