apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  namespace: aidp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: local-model-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow:5000
            - name: MODEL_NAME
              value: iris-classifier
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio:9000
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: model-api
  namespace: aidp
spec:
  selector:
    app: model-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP